dcat:
  distributie_pad : ../resources/be/vlaanderen/omgeving/data/id/dataset/codelijst-testrepo/
  distributie_naam: catalog
  jsonld_source : ../resources/source/catalog_context.json
  csv_source : ../resources/source/catalog_source.csv
skos:
  distributie_pad: ../resources/be/vlaanderen/omgeving/data/id/conceptscheme/testrepo/
  distributie_naam: testrepo
  jsonld_source: ../resources/source/codelijst_context.json
  csv_source: ../resources/source/codelijst_source.csv
