dcat:
  distributie_pad : ../resources/be/vlaanderen/omgeving/data/id/dataset/codelijst-testrepo/
  jsonld_source : ../resources/source/catalog_context.json
  csv_source : ../resources/source/catalog_source.csv
